# Site
name: "JJIKKYU"
title: "미공대생 | JJIKKYU"
description: "Hongik Univ. Digital Media Deseign, Game Software"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://jjikkyu.github.io
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jjikkyu:
    name: JJIKKYU
    display_name: JJIKKYU
    avatar: 'assets/images/avatar.png'
    email: jjinggu96@gmail.com
    web: https://youtube.com/JJIKKYU
    twitter: https://youtube.com/JJIKKYU
    description: "안녕하세요. 미공대생 JJIKKYU입니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
